[package]
name = "hangman"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.13"
rand = "0.9.2"
reqwest = { version = "0.13.1", features = ["blocking"] }
